export const products = [
  {
    id: 1,
    title: "Apple",
    name: "AAPL",
    price: 132.54,
    stock: 2,
    symbol: "AAPL",
    currency: "USD",
    description:
      "Apple Inc. diseña, fabrica y comercializa teléfonos inteligentes, computadoras personales, tabletas, dispositivos portátiles y accesorios en todo el mundo.",
    category: "acciones",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681939649/glsphqznluxremekcrwu.png",
  },
  {
    id: 2,
    title: "amazon",
    name: "AMZN",
    price: 3346.83,
    stock: 5,
    symbol: "AMZN",
    currency: "USD",
    description:
      "Amazon.com, Inc. se dedica a la venta minorista de productos de consumo y suscripciones en América del Norte e internacionalmente.",
    category: "Cedears",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681939769/ptsgx2ulxw1whkkfgtzn.png",
  },
  {
    id: 3,
    title: "google",
    name: "GOOGL",
    price: 2292.76,
    stock: 7,
    symbol: "GOOGL",
    currency: "USD",
    description:
      "Alphabet Inc. ofrece servicios de publicidad en línea en los Estados Unidos, Europa, Medio Oriente, África, Asia-Pacífico, Canadá y América Latina.",
    category: "Bonos",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681939873/jogdovzyglmvrjptt5lb.png",
  },
  {
    id: 4,
    title: "tesla",
    name: "TSLA",
    price: 701.98,
    stock: 3,
    symbol: "TSLA",
    currency: "USD",
    description:
      "Tesla, Inc. diseña, desarrolla, fabrica y vende vehículos eléctricos y sistemas de generación y almacenamiento de energía en Estados Unidos, China, Países Bajos, Noruega e internacionalmente.",
    category: "Fondos",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681939988/llxcohdhtvquddvu9exp.png",
  },
  {
    id: 5,
    title: "microsoft",
    name: "MSFT",
    price: 261.41,
    stock: 7,
    symbol: "MSFT",
    currency: "USD",
    description:
      "Microsoft Corporation desarrolla, licencia y ofrece soporte para software, servicios, dispositivos y soluciones en todo el mundo.",
    category: "Cauciones",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681940002/s2j3nm6sonr0ypv0hpi9.png",
  },
  {
    id: 6,
    title: "ford",
    name: "F",
    price: 13.78,
    stock: 1,
    symbol: "F",
    currency: "USD",
    description:
      "Ford Motor Company diseña, fabrica, comercializa y presta servicios a una variedad de vehículos Ford, camiones, vehículos utilitarios deportivos, vehículos electrificados y vehículos de lujo Lincoln en todo el mundo.",
    category: "Cheques",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681940017/l0uqqiiusinjhqm5dcjs.jpg",
  },
  {
    id: 7,
    title: "walmart",
    name: "WMT",
    price: 140.74,
    stock: 12,
    symbol: "WMT",
    currency: "USD",
    description:
      "Walmart Inc. se dedica a las operaciones minoristas y mayoristas en varios formatos en todo el mundo.",
    category: "Monedas",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681940031/bjycbbkwxkm9cjaxbmoi.png",
  },
  {
    id: 8,
    title: "JP",
    name: "JP Morgan Chase",
    price: 133.42,
    stock: 22,
    symbol: "JPM",
    currency: "USD",
    description:
      "JP Morgan Chase & Co. es una de las principales firmas de servicios financieros globales y una de las instituciones bancarias más grandes de los Estados Unidos.",
    category: "Obligaciones negociables",
    img: "https://res.cloudinary.com/dfbl1tifi/image/upload/v1681940045/ifkf74lfpje00c4bx6tl.png",
  },
];
